### ISSUE TITLE
is there any way to work with torchvision 0.9.0 instead of 0.8.2 ?

### ISSUE THREAD

**Issue by nickums** [openai/CLIP#106]
Is there any way I can install and run with torchvision 0.9.0?
I have this version and pip  cannot find the 0.8.2 required by  CLIP

**Comment by torridgristle** [comment]
I can run CLIP without issue on PyTorch 1.8.1+cu101 and Torchvision 0.9.1+cu101 with a small change. I compared 1000 image encodes with and without this change, the difference seems small and the cosine similarity between the encodes with and without the change were all 1.0 or 0.999 aside from one outlier.

If you have everything you need to run CLIP, just not the old versions of things it asks for, install it with
```
pip install --no-deps git+https://github.com/openai/CLIP.git
pip install --no-deps ftfy regex tqdm
```
and load CLIP with `clip.load("ViT-B/32", jit=False)`. It needed the jit=False for a reason unknown to me.

**Comment by nickums** [comment]
many thanks for that extremely helpful info, --no-deps is a revelation.
I now have to wrestle with 'AttributeError: module 'clip' has no attribute 'load'

**Comment by jongwook** [comment]
A recent commit (db20393f4affd4158528bd868478e516ebed0944) removed the specific torch and torchvision versions from `requirements.txt` to avoid the dependency hell and also the conda/pip UX fiasco to some degree. Now the code should work okay with reasonably recent torch/torchvision although future updates may break these anytime. I'd still recommend pinning their versions that works for your application!
